config/routes.rb
Rails.application.routes.draw do
  resources :serverdetails
  root "serverdetails#index"
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
	   
      resources :serverdetails, only: [:index, :create, :show, :update, :destroy]
     # resources :microposts, only: [:index, :create, :show, :update, :destroy]
	 
    end
  end
  
   # mount API::Base, at: "/"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/serverdetail.rb
class Serverdetail < ApplicationRecord
end

app/controllers/api/v1/serverdetails_controller.rb
class Api::V1::ServerdetailsController < ApplicationController
#class ServerdetailsController < ApplicationController
  before_action :set_serverdetail, only: [:show, :edit, :update, :destroy]
  
  # GET /serverdetails
  def index
    @serverdetails = Serverdetail.all
	        render json: @serverdetails
  end

  # GET /serverdetails/1
  def show
  	        render json: @serverdetail

  end

  # GET /serverdetails/new
  def new
    @serverdetail = Serverdetail.new
  end

  # GET /serverdetails/1/edit
  def edit
  end

  # POST /serverdetails
  def create
    @serverdetail = Serverdetail.new(serverdetail_params)

    if @serverdetail.save
      render json: @serverdetail, redirect_to @serverdetail, notice: 'Serverdetail was successfully created.'
    else
       render json: @servdetail.errors, render :new
    end
  end

  # PATCH/PUT /serverdetails/1
  def update
    if @serverdetail.update(serverdetail_params)
            render json: @serverdetail,redirect_to @serverdetail, notice: 'Serverdetail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /serverdetails/1
  def destroy
    @serverdetail.destroy
    redirect_to serverdetails_url, notice: 'Serverdetail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serverdetail
      @serverdetail = Serverdetail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def serverdetail_params
      params.require(:serverdetail).permit(:servername, :cpu, :disk, :process)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/serverdetails_controller.rb
class ServerdetailsController < ApplicationController
  before_action :set_serverdetail, only: [:show, :edit, :update, :destroy]

  # GET /serverdetails
  def index
    @serverdetails = Serverdetail.all
  end

  # GET /serverdetails/1
  def show
  end

  # GET /serverdetails/new
  def new
    @serverdetail = Serverdetail.new
  end

  # GET /serverdetails/1/edit
  def edit
  end

  # POST /serverdetails
  def create
    @serverdetail = Serverdetail.new(serverdetail_params)

    if @serverdetail.save
      redirect_to @serverdetail, notice: 'Serverdetail was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /serverdetails/1
  def update
    if @serverdetail.update(serverdetail_params)
      redirect_to @serverdetail, notice: 'Serverdetail was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /serverdetails/1
  def destroy
    @serverdetail.destroy
    redirect_to serverdetails_url, notice: 'Serverdetail was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_serverdetail
      @serverdetail = Serverdetail.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def serverdetail_params
      params.require(:serverdetail).permit(:servername, :cpu, :disk, :process)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/serverdetails_helper.rb
module ServerdetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/serverdetails/_form.html.erb
<%= form_with(model: serverdetail, local: true) do |form| %>
  <% if serverdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(serverdetail.errors.count, "error") %> prohibited this serverdetail from being saved:</h2>

      <ul>
      <% serverdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :servername %>
    <%= form.text_field :servername, id: :serverdetail_servername %>
  </div>

  <div class="field">
    <%= form.label :cpu %>
    <%= form.number_field :cpu, id: :serverdetail_cpu %>
  </div>

  <div class="field">
    <%= form.label :disk %>
    <%= form.number_field :disk, id: :serverdetail_disk %>
  </div>

  <div class="field">
    <%= form.label :process %>
    <%= form.number_field :process, id: :serverdetail_process %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/serverdetails/edit.html.erb
<h1>Editing Serverdetail</h1>

<%= render 'form', serverdetail: @serverdetail %>

<%= link_to 'Show', @serverdetail %> |
<%= link_to 'Back', serverdetails_path %>

app/views/serverdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Serverdetails</h1>

<table>
  <thead>
    <tr>
      <th>Servername</th>
      <th>Cpu</th>
      <th>Disk</th>
      <th>Process</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @serverdetails.each do |serverdetail| %>
      <tr>
        <td><%= serverdetail.servername %></td>
        <td><%= serverdetail.cpu %></td>
        <td><%= serverdetail.disk %></td>
        <td><%= serverdetail.process %></td>
        <td><%= link_to 'Show', serverdetail %></td>
        <td><%= link_to 'Edit', edit_serverdetail_path(serverdetail) %></td>
        <td><%= link_to 'Destroy', serverdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Serverdetail', new_serverdetail_path %>

app/views/serverdetails/new.html.erb
<h1>New Serverdetail</h1>

<%= render 'form', serverdetail: @serverdetail %>

<%= link_to 'Back', serverdetails_path %>

app/views/serverdetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Servername:</strong>
  <%= @serverdetail.servername %>
</p>

<p>
  <strong>Cpu:</strong>
  <%= @serverdetail.cpu %>
</p>

<p>
  <strong>Disk:</strong>
  <%= @serverdetail.disk %>
</p>

<p>
  <strong>Process:</strong>
  <%= @serverdetail.process %>
</p>

<%= link_to 'Edit', edit_serverdetail_path(@serverdetail) %> |
<%= link_to 'Back', serverdetails_path %>